spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: db,jwt,oauth2
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope: profile, email

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}
